package com.chandu.ctcp.enums;


public enum ComplaintType {
    LETTER_OF_CREDIT,
    IMPORT_BILL_UNDER_LC,
    EXPORT_BILL_UNDER_LC,
    IMPORT_BILL_UNDER_COLLECTION,
    EXPORT_BILL_UNDER_COLLECTION,
    PRE_SHIPMENT_FINANCE,
    BILL_DISCOUNTING,
    A1_A2_REMITTANCE,
    BANK_GUARANTEE
}
