spring.application.name=eureka-server
server.port=8761

# Eureka server shouldn't try to register with itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# optional: show debug info on startup
management.endpoints.web.exposure.include=*
