spring.application.name=one-to-one-mapping


spring.datasource.url=jdbc:mysql://localhost:3306/dilip_it
spring.datasource.username=root
spring.datasource.password=chandu221299

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update