spring.application.name=user-service
server.port=8081
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
# optional: shorter heartbeat/lease for faster demo removal (be careful in prod)
eureka.instance.leaseRenewalIntervalInSeconds=5
eureka.instance.prefer-ip-address=true
