#server.port=8080
#spring.application.name=api-gateway
#
#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true
#
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#
#
########################################################
## 1?? STATIC ROUTES (Recommended to keep both options)
########################################################
#
## Route for USER SERVICE
#spring.cloud.gateway.routes[0].id=user-service
#spring.cloud.gateway.routes[0].uri=lb://user-service
#spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**
#spring.cloud.gateway.routes[0].filters[0]=AuthenticationFilter
#
## Route for PRODUCT SERVICE
#spring.cloud.gateway.routes[1].id=product-service
#spring.cloud.gateway.routes[1].uri=lb://product-service
#spring.cloud.gateway.routes[1].predicates[0]=Path=/products/**
#spring.cloud.gateway.routes[1].filters[1]=AuthenticationFilter
#
## Route for AUTH SERVICE
#spring.cloud.gateway.routes[2].id=auth-service
#spring.cloud.gateway.routes[2].uri=lb://auth-service
#spring.cloud.gateway.routes[2].predicates[0]=Path=/auth/**